name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: rustup toolchain install nightly
    - name: Build
      run: cargo +nightly build --verbose
    - name: Run tests
      run: cargo +nightly test --all --verbose
